[package]
name = "retina-gfx"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
retina-common = { path = "../retina-common" }

futures = "*"
bytemuck = "*"
euclid = "*"
log = "*"
winit = "0.28.6"
wgpu = "*"
wgpu_glyph = "*"
