[package]
name = "retina-gfx"
version.workspace = true
edition.workspace = true

[dependencies]
retina-common = { path = "../retina-common" }

futures = "*"
euclid = "*"
winit = "0.28.3"
wgpu = "*"
wgpu_glyph = "*"
