[package]
name = "retina-compositor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
retina-gfx = { path = "../retina-gfx" }
retina-layout = { path = "../retina-layout" }
retina-style = { path = "../retina-style" }

wgpu = "*"
