[package]
name = "retina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "*"
gleam = "0.13"
glutin = "0.28"
html5ever = "*"
http = "*"
http-body-util = "0.1.0-rc.2"
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
webrender = { git = "https://github.com/servo/webrender" }
winit = "0.26"
