[workspace]
members = [
    "retina",
    "retina-common",
    "retina-dom",
    "retina-gfx",
    "retina-layout",
    "retina-page",
    "retina-style",
    "retina-style-computation",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
