[package]
name = "font-kit-c"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]

[dependencies.font-kit]
path = ".."

[build-dependencies]
cbindgen = "0.8"
