name: CI

on:
  push:
    branches: [auto]
  pull_request:
  workflow_dispatch:

jobs:
  windows-ci:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cargo build
        run: cargo build --no-default-features

      - name: Cargo test
        run: cargo test --verbose
        env:
          RUST_BACKTRACE: 1

  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    needs:
      - "windows-ci"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
