[package]
name = "retina-gfx-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
euclid = "*"
thiserror = "*"
raw-window-handle = "*"

[target.'cfg(windows)'.dependencies]
winsafe = { version = "*", features = [
    "gui"
] }
muda = "*"
