[package]
name = "retina-fetch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
retina-user-agent = { path = "../retina-user-agent" }

futures-core = "*"

tokio = { version = "*", features = [
    "full" # TODO
] }

tokio-util = { version = "*", features = [
    "codec",
] }

hyper = { version = "*", features = [
    "client",
    "http1",
    "http2",
    "stream",
] }

hyper-tls = "*"
url = "*"

[dev-dependencies]
rstest = "*"
