[package]
name = "retina-style"
version.workspace = true
edition.workspace = true

[dependencies]
retina-common = { path = "../retina-common" }

cssparser = "*"
log = "*"
strum = { version = "*", features = ["derive"] }
tendril = "*"

[dev-dependencies]
rstest = "*"
