[package]
name = "retina"
version.workspace = true
edition.workspace = true

[dependencies]
retina-gfx = { path = "../retina-gfx" }

env_logger = "*"
html5ever = "*"
http = "*"
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
