[package]
name = "retina"
version.workspace = true
edition.workspace = true

[dependencies]
retina-gfx = { path = "../retina-gfx" }
retina-page = { path = "../retina-page" }

env_logger = "*"
url = "*"
