[package]
name = "retina-SUBCRATE"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Reserved for a component of the Retina browser"

[dependencies]
