[package]
name = "retina-SUBCRATE"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/usadson/retina"
homepage = "https://github.com/usadson/retina"
description = "Reserved for a component of the Retina browser"

[dependencies]
