[package]
name = "retina-user-agent"
version.workspace = true
edition.workspace = true

[dev-dependencies]
retina-style = { path = "../retina-style" }
retina-style-parser = { path = "../retina-style-parser" }

pretty_assertions = "*"
